include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true # AG-CORE-006
    unawaited_futures: true
    directives_ordering: true
